CREATE TABLE api_car (
    id INT SERIAL PRIMARY KEY,
    Model_Xe VARCHAR(255),
    Nam_San_Xuat INT,
    Gia_Tien DECIMAL(10, 2),
    Xuat_Xu VARCHAR(255),
    Tinh_Trang INT,
    Dong_Xe VARCHAR(255),
    So_KM_Da_Di INT,
    Mau_Ngoai_That VARCHAR(255),
    Mau_Noi_That VARCHAR(255),
    So_Cho_Ngoi INT,
    Dong_Co VARCHAR(255),
    He_Thong_Nap_Nhien_Lieu VARCHAR(255),
    Hop_So VARCHAR(255),
    Dan_Dong VARCHAR(255),
    Thanh_Pho_MPG INT,
    Cao_Toc_MPG INT,
    Chieu_Dai_Co_So DECIMAL(5, 1),
    Chieu_Dai_Xe DECIMAL(5, 1),
    Chieu_Rong_Xe DECIMAL(5, 1),
    Chieu_Cao_Xe DECIMAL(5, 1),
    Do_Nang INT,
    Kich_Thuoc_Dong_Co DECIMAL(4, 1),
    Ty_So_Duong_Kinh_Xy_Lanh_Pit_Tong DECIMAL(3, 2),
    Stroke DECIMAL(3, 2),
    Ma_Luc INT,
    So_Vong_Quay_Cuc_Dai INT,
    Dia_Chi VARCHAR(255)
);
